#!/usr/bin/env node
// scripts/build-seed.js
//
// Reads data/case.json and generates data/seed.sql.
// Run from the project root: node scripts/build-seed.js
//
// WHY: editing SQL INSERT statements by hand is error-prone and hard to read.
// case.json is human-friendly JSON — easy to rename a character, change an
// address, or add a new person. This script does the SQL generation for you.
//
// Add new tables: add their key to the TABLE_ORDER array and make sure
// case.json has a matching array at the top level (e.g. "people", "addresses").

const fs   = require('fs');
const path = require('path');

const DATA_DIR  = path.join(__dirname, '..', 'data');
const CASE_FILE = path.join(DATA_DIR, 'case.json');
const SEED_FILE = path.join(DATA_DIR, 'seed.sql');

// The order in which tables are populated.
// Tables must be listed AFTER the tables they reference
// (e.g. addresses before people if people had a real FK — SQLite doesn't
// enforce FKs by default, but good practice).
const TABLE_ORDER = [
  'addresses',
  'people',
  'phone_calls',
  'bank_records',
  'interviews',
  'crime_scene_reports',
  'evidence',
  'sightings',
  'vehicles',
  'club_bookings',
  'newspaper_archive',
  'precinct_logs',
  'relationships',
  'confidential_notes',
];

// ============================================================
// HELPERS
// ============================================================

/**
 * Converts a JavaScript value to a SQL literal.
 * Numbers → bare number, null/undefined → NULL, everything else → quoted string.
 * Single quotes inside strings are escaped by doubling them (SQL standard).
 */
function sqlVal(val) {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number')           return String(val);
  if (typeof val === 'boolean')          return val ? '1' : '0';
  // Escape single quotes and wrap in single quotes
  return `'${String(val).replace(/'/g, "''")}'`;
}

/**
 * Generates INSERT statements for all rows in an array.
 * Each object in the array becomes one INSERT.
 * All objects must have the same keys (the first row defines the columns).
 */
function generateInserts(tableName, rows) {
  if (!rows || rows.length === 0) {
    return `-- ${tableName}: no data\n`;
  }

  const columns = Object.keys(rows[0]);
  let out = `-- ${tableName}\n`;

  for (const row of rows) {
    const vals = columns.map(col => sqlVal(row[col]));
    out += `INSERT INTO ${tableName} (${columns.join(', ')}) VALUES (${vals.join(', ')});\n`;
  }

  return out + '\n';
}

// ============================================================
// MAIN
// ============================================================

function main() {
  // Read case.json
  if (!fs.existsSync(CASE_FILE)) {
    console.error(`Error: case.json not found at ${CASE_FILE}`);
    process.exit(1);
  }

  let caseData;
  try {
    caseData = JSON.parse(fs.readFileSync(CASE_FILE, 'utf8'));
  } catch (err) {
    console.error(`Error: could not parse case.json — ${err.message}`);
    process.exit(1);
  }

  // Build the output SQL
  let sql = `-- seed.sql — GENERATED by scripts/build-seed.js from data/case.json\n`;
  sql    += `-- Do not hand-edit this file. Edit case.json and re-run:\n`;
  sql    += `--   node scripts/build-seed.js\n`;
  sql    += `-- Generated: ${new Date().toISOString()}\n\n`;

  const counts = {};
  for (const table of TABLE_ORDER) {
    const rows = caseData[table];
    if (!Array.isArray(rows)) {
      console.warn(`Warning: no array found for table "${table}" in case.json — skipping.`);
      counts[table] = 0;
      continue;
    }
    sql += generateInserts(table, rows);
    counts[table] = rows.length;
  }

  // Write to disk
  fs.writeFileSync(SEED_FILE, sql, 'utf8');

  // Summary
  console.log('\n✓ seed.sql generated\n');
  for (const [table, count] of Object.entries(counts)) {
    console.log(`  ${table.padEnd(20)} ${count} row${count !== 1 ? 's' : ''}`);
  }
  console.log(`\n  Output: ${SEED_FILE}\n`);
}

main();
